model:
  base_learning_rate: 1.5e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    cond_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: ./logs/2024-10-23T21-11-09_shape_model_tiny/checkpoints/epoch=000029.ckpt
        monitor: val/rec_loss
        embed_dim: 1
        ddconfig:
          double_z: true
          z_channels: 1
          resolution: 128
          in_channels: 1
          out_ch: 1
          ch: 32
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    first_stage_key: image # key til batch dict for pixel input
    cond_stage_key: shape # if different from first_stage_key, this will be input so ddpm
    image_size: 32 # used for z_T sampling
    channels: 2 # used for z_T sampling
    cond_stage_trainable: false # in the batch for the datalaoder, give vertebrae_embedding as tensor the same dim order as image
    conditioning_key: concat
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 3
        model_channels: 96
        out_channels: 2
        num_res_blocks: 2
        attention_resolutions:
        - 2
        - 4
        - 8
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        conv_resample: false
        num_head_channels: 16
        use_spatial_transformer: False
        transformer_depth: 1
        # context_dim: 256
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: ./logs/2024-10-24T14-50-25_height_model_small/checkpoints/epoch=000016.ckpt
        monitor: val/rec_loss
        embed_dim: 2
        ddconfig:
          double_z: true
          z_channels: 2
          resolution: 128
          in_channels: 1
          out_ch: 1
          ch: 96
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 25
    wrap: false
    train:
      target: height_dataset.HeightData
      params:
        path: ../data/height_contours/df_128/df.shp
        root_dir: ../
        im_size: 128
        mode: train
    validation:
      target: height_dataset.HeightData
      params:
        path: ../data/height_contours/df_128/df.shp
        root_dir: ../
        im_size: 128
        mode: val
