checkpointing:
  every_n_epochs: 1
  mode: min
  save_top_k: 5
dataloader:
  batch_size: 8
  num_workers: 20
  persistent_workers: true
  pin_memory: false
  val_worker_ratio: 0.1
dataset:
  params:
    cutout_overlap: 64
    data_split_seed: 42
    img_size: 128
    max_cities: 10000
    max_epoch_length: 1000000
    min_cities: 10
    processed_data_path: CityGeneration/data
    smoothing: 10
    unprocessed_data_path: data/undistorted_data_ortho_3
    val_split: 0.2
    verbose: true
  target: CityGeneration.src.dataset.city_dataloader.CityDataset
identifier:
  name: train
  time_format: '%m%d'
inference:
  params:
    img_size: 128
  target: CityGeneration.model.inference_model.InferenceModel
logging:
  dir: CityGeneration/out/logs
  log_every_n_steps: 1
  log_gradients:
    every_n: 100
    step_type: batch
    use: true
  log_pred:
    every_n: 1
    step_type: epoch
    use: true
seed: 42
training:
  accelerator: auto
  accumulate_grad_batches: 50
  epochs: 10000
  gradient_clipping:
    algorithm: norm
    use: true
    value: 1.0
  loss_functions:
  - params:
      log_target: false
      reduction: batchmean
    target: CityGeneration.src.losses.kl_divergence.KLDivergence
    weight: 1
  optimizer:
    lr_half_period: 50
    lr_max: 1e-4
    lr_min: 1e-5
    lr_mult_period: 2
    lr_warmup_max: 4e-4
    lr_warmup_period: 20
    optimizer: adamw
    weight_decay: 0
  precision: 32-true
