model:
  base_learning_rate: 1.0e-05
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    im_recon_mode: continuous
    monitor: val/rec_loss
    embed_dim: 2
    lossconfig:
      target: ldm.modules.losses.custom_loses.ContinuousBernoulliWithDiscriminator
      params:
        disc_start: 4001000000
        kl_weight: 1.0e-06
        disc_weight: 0.05
        disc_in_channels: 1
        disc_num_layers: 2
        perceptual_weight: 0.0
    ddconfig:
      double_z: true
      z_channels: 2
      resolution: 128
      in_channels: 1
      out_ch: 1
      ch: 64
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    wrap: false
    train:
      target: height_dataset.HeightData
      params:
        path: '../data/height_contours/df_128/df.shp'
        root_dir: '../'
        im_size: 128
        mode: train
    validation:
      target: height_dataset.HeightData
      params:
        path: '../data/height_contours/df_128/df.shp'
        root_dir: '../'
        im_size: 128
        mode: val
