model:
  base_learning_rate: 1.0e-05
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 1
    lossconfig:
      target: ldm.modules.losses.custom_loses.BernoulliWithDiscriminator
      params:
        disc_start: 4001
        kl_weight: 1.0e-06
        disc_weight: 0.05
        disc_in_channels: 1
        disc_num_layers: 2
        perceptual_weight: 0.0
    ddconfig:
      double_z: true
      z_channels: 1
      resolution: 128
      in_channels: 1
      out_ch: 1
      ch: 32
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: false
    train:
      target: shape_dataset.ShapeData
      params:
        path: '../data/contours/df_128/df.shp'
        im_size: 128
        mode: train
    validation:
      target: shape_dataset.ShapeData
      params:
        path: '../data/contours/df_128/df.shp'
        im_size: 128
        mode: val
